development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: littlebits_development
  pool:     5
  username: jperkins
  password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: littlebits_test
  pool:     5
  username: jperkins
  password:
  template: template0
